### ISSUE TITLE
How can i load multiple vite sub apps simultaneously?

### ISSUE THREAD

**Issue by Relaxe111** [tengmaoqing/vite-plugin-qiankun#35]
Hi, need to load multiple micro apps simultaneously is there any possibility to achieve that with vite-plugin-qiankun?

**Comment by Relaxe111** [comment]
I found out what is the problem.  loadApp function from qiankun set global (window) object sandboxed. and all life cycles methods including those from vite are set to that global sandboxed state (sandboxed: false, not solves problem because of same problem, i tried). When one loads more than one app simultaneously global object overrides and when application scripts executes only last application will be rendered because both application will have only one global object which was overridden by last loadApp function. In order to fix this issue I had to add two lines of code in loader.ts (qiankun) right before return of the loadApp fn:
 
```
//loader.ts (qiankun)
export async function loadApp<T extends ObjectType>(
    app: LoadableApp<T>,
    configuration: FrameworkConfiguration = {},
    lifeCycles?: FrameworkLifeCycles<T>,
): Promise<ParcelConfigObjectGetter> {

    ....

    window.__GLOBAL_CONCURENT_QIANKUN__[appName] = global
    global.__GLOBAL_CONCURENT_QIANKUN__ = window.__GLOBAL_CONCURENT_QIANKUN__

    return parcelConfigGetter
}
```
and in vite-plugin-qiankun have added some code in two places:
in helpers.ts I added window.__GLOBAL_CONCURENT_QIANKUN__?.[``${appName}``] like:
```
// helper.ts
export const qiankunWindow: QiankunWindow =
    typeof window !== 'undefined'
        ? window.__GLOBAL_CONCURENT_QIANKUN__?.['asma-app-chat'] || window.proxy || window
        : {}
```
in second place i have reassigned window.proxy = window.__GLOBAL_CONCURENT_QIANKUN__?.[`${appName}`] in createImportFinallyResolve function like:
```
// index.ts 
const createImportFinallyResolve = (qiankunName: string) => {
    return `
    window.proxy = window.proxy.__GLOBAL_CONCURENT_QIANKUN__['${qiankunName}']
    const qiankunLifeCycle = window.moduleQiankunAppLifeCycles && 
    window.moduleQiankunAppLifeCycles['${qiankunName}'];
    
    if (qiankunLifeCycle) {
      window.proxy.vitemount((props) => return qiankunLifeCycle.mount(props));
      window.proxy.viteunmount((props) => qiankunLifeCycle.unmount(props));
      window.proxy.vitebootstrap(() => qiankunLifeCycle.bootstrap());
      window.proxy.viteupdate((props) => qiankunLifeCycle.update(props));
    }
  `
}
```
I am sure there could be found a more elegant way of solving this. I will be happy to hear for better solutions.

I would like to make a pr if my fix make sense and is usable for more peoples.
but it looks like there is need to add 2 lines of code in qiankun as well.

**Comment by legend-li** [comment]
qiankun3.0 promise support vite, but qinkun3.0 is development. before qiankun3.0 online, we can use this method to fix this problem.

**Comment by legend-li** [comment]
my solution is:

qiankun changes like:

``` js
//loader.ts changes (qiankun)
export async function loadApp<T extends ObjectType>(
    app: LoadableApp<T>,
    configuration: FrameworkConfiguration = {},
    lifeCycles?: FrameworkLifeCycles<T>,
): Promise<ParcelConfigObjectGetter> {

    ....

    if (!window.__GLOBAL_CONCURENT_QIANKUN__) {
        window.__GLOBAL_CONCURENT_QIANKUN__ = {};
    }
    console.log('appName:', appName);
    window.__GLOBAL_CONCURENT_QIANKUN__[appName] = global;
    global.__GLOBAL_CONCURENT_QIANKUN__ = window.__GLOBAL_CONCURENT_QIANKUN__;
  
    return parcelConfigGetter
}
```

vite-plugin-qiankun changes like:

helper.ts file changes:
``` js
// helper.ts changes (vite-plugin-qiankun)

// Discard qiankunWindow export.
// export const qiankunWindow: QiankunWindow = typeof window !== 'undefined' ? window.__GLOBAL_CONCURENT_QIANKUN__?.['idc-admin'] || window.proxy || window : {}

// Obtain qiankunWindow through  getQiankunWindow.
export const getQiankunWindow = (qiankunName: string) => typeof window !== 'undefined' ? window.__GLOBAL_CONCURENT_QIANKUN__?.[qiankunName] || window.proxy || window : {}

// Function renderWithQiankun add argument qiankunWindow.
export const renderWithQiankun = (qiankunLifeCycle: QiankunLifeCycle, qiankunWindow: QiankunWindow) => {
  // 函数只有一次执行机会，需要把生命周期赋值给全局
  if (qiankunWindow?.__POWERED_BY_QIANKUN__) {
    if (!window.moudleQiankunAppLifeCycles) {
      window.moudleQiankunAppLifeCycles = {}
    }
    if (qiankunWindow.qiankunName) {
      window.moudleQiankunAppLifeCycles[qiankunWindow.qiankunName] = qiankunLifeCycle
    }
  }
}
```

index.ts file changes:
``` js
// index.ts changes (vite-plugin-qiankun)
const createImportFinallyResolve = (qiankunName: string) => {
  return `
    window.proxy = window.proxy.__GLOBAL_CONCURENT_QIANKUN__['${qiankunName}']
    const qiankunLifeCycle = window.moudleQiankunAppLifeCycles && window.moudleQiankunAppLifeCycles['${qiankunName}'];
    if (qiankunLifeCycle) {
      window.proxy.vitemount((props) => qiankunLifeCycle.mount(props));
      window.proxy.viteunmount((props) => qiankunLifeCycle.unmount(props));
      window.proxy.vitebootstrap(() => qiankunLifeCycle.bootstrap());
      window.proxy.viteupdate((props) => qiankunLifeCycle.update(props));
    }
  `
}

```

**Comment by ylingl13** [comment]
> my solution is:
> 
> qiankun changes like:
> 
> ```js
> //loader.ts changes (qiankun)
> export async function loadApp<T extends ObjectType>(
>     app: LoadableApp<T>,
>     configuration: FrameworkConfiguration = {},
>     lifeCycles?: FrameworkLifeCycles<T>,
> ): Promise<ParcelConfigObjectGetter> {
> 
>     ....
> 
>     if (!window.__GLOBAL_CONCURENT_QIANKUN__) {
>         window.__GLOBAL_CONCURENT_QIANKUN__ = {};
>     }
>     console.log('appName:', appName);
>     window.__GLOBAL_CONCURENT_QIANKUN__[appName] = global;
>     global.__GLOBAL_CONCURENT_QIANKUN__ = window.__GLOBAL_CONCURENT_QIANKUN__;
>   
>     return parcelConfigGetter
> }
> ```
> 
> vite-plugin-qiankun changes like:
> 
> helper.ts file changes:
> 
> ```js
> // helper.ts changes (vite-plugin-qiankun)
> 
> // Discard qiankunWindow export.
> // export const qiankunWindow: QiankunWindow = typeof window !== 'undefined' ? window.__GLOBAL_CONCURENT_QIANKUN__?.['idc-admin'] || window.proxy || window : {}
> 
> // Obtain qiankunWindow through  getQiankunWindow.
> export const getQiankunWindow = (qiankunName: string) => typeof window !== 'undefined' ? window.__GLOBAL_CONCURENT_QIANKUN__?.[qiankunName] || window.proxy || window : {}
> 
> // Function renderWithQiankun add argument qiankunWindow.
> export const renderWithQiankun = (qiankunLifeCycle: QiankunLifeCycle, qiankunWindow: QiankunWindow) => {
>   // 函数只有一次执行机会，需要把生命周期赋值给全局
>   if (qiankunWindow?.__POWERED_BY_QIANKUN__) {
>     if (!window.moudleQiankunAppLifeCycles) {
>       window.moudleQiankunAppLifeCycles = {}
>     }
>     if (qiankunWindow.qiankunName) {
>       window.moudleQiankunAppLifeCycles[qiankunWindow.qiankunName] = qiankunLifeCycle
>     }
>   }
> }
> ```
> 
> index.ts file changes:
> 
> ```js
> // index.ts changes (vite-plugin-qiankun)
> const createImportFinallyResolve = (qiankunName: string) => {
>   return `
>     window.proxy = window.proxy.__GLOBAL_CONCURENT_QIANKUN__['${qiankunName}']
>     const qiankunLifeCycle = window.moudleQiankunAppLifeCycles && window.moudleQiankunAppLifeCycles['${qiankunName}'];
>     if (qiankunLifeCycle) {
>       window.proxy.vitemount((props) => qiankunLifeCycle.mount(props));
>       window.proxy.viteunmount((props) => qiankunLifeCycle.unmount(props));
>       window.proxy.vitebootstrap(() => qiankunLifeCycle.bootstrap());
>       window.proxy.viteupdate((props) => qiankunLifeCycle.update(props));
>     }
>   `
> }
> ```
How to use it? Do you have any examples， and how to dynamically assign values to "qiankunName",Thank you!

**Comment by youthug** [comment]
Has anyone encountered this error after using the edited version of qiankun? I have both Vue 2 and Vue 3 micro apps, and this error occurred in a Vue 2 micro app that uses the Select component from Element-UI. An exception occurs when clicking the input to open the select dropdown.

```
TypeError: Illegal invocation
    at window.addEventListener (qiankun.js?v=43329dcf:1188:17)
    at global2.addEventListener (qiankun.js?v=43329dcf:4288:32)
    at Popper._setupEventListeners (popper.js:457:1)
    at new Popper (popper.js:195:1)
    at VueComponent.createPopper (vue-popper.js:117:1)
    at VueComponent.updatePopper (vue-popper.js:137:1)
    at VueComponent.updatePopper (db-el-widgets.common.js:4676:1)
    at VueComponent.eval (db-el-widgets.common.js:4666:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:3017:1)
    at Vue.$emit (vue.runtime.esm.js:3716:1)
```

**Comment by youthug** [comment]
> Has anyone encountered this error after using the edited version of qiankun? I have both Vue 2 and Vue 3 micro apps, and this error occurred in a Vue 2 micro app that uses the Select component from Element-UI. An exception occurs when clicking the input to open the select dropdown.
> 
> ```
> TypeError: Illegal invocation
>     at window.addEventListener (qiankun.js?v=43329dcf:1188:17)
>     at global2.addEventListener (qiankun.js?v=43329dcf:4288:32)
>     at Popper._setupEventListeners (popper.js:457:1)
>     at new Popper (popper.js:195:1)
>     at VueComponent.createPopper (vue-popper.js:117:1)
>     at VueComponent.updatePopper (vue-popper.js:137:1)
>     at VueComponent.updatePopper (db-el-widgets.common.js:4676:1)
>     at VueComponent.eval (db-el-widgets.common.js:4666:1)
>     at invokeWithErrorHandling (vue.runtime.esm.js:3017:1)
>     at Vue.$emit (vue.runtime.esm.js:3716:1)
> ```

I checked qiankun's commit history and found this: https://github.com/umijs/qiankun/commit/cbd6cc064624be31a5f5f972d37075471ac7b15a. This might be a faulty fix or something else. I reset it to tag v2.10.16, and now everything works again 🎉
